services:
  - type: web
    name: peter-md
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SESSION_ID
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: OWNER_NUMBER
        value: "255682211773"
      - key: SUDO
        value: "255682211773"
      - key: MODE
        value: "public"
      - key: PREFIX
        value: "."
      - key: APP_URL
        sync: false
